### ISSUE TITLE
Problem on xammp and windows server

### ISSUE THREAD

**Issue by nanoziobelo** [cwacha/iaddressbook#11] opened 2021-04-10 10:11 UTC
Hi 
I copy file in folder and make installation step but when finish give error on redirect
http://localhost/Rubrica/index.php/home and page not view

**Comment by cwacha** [comment] 2021-04-10 14:07
Hi

This is a known bug. Please ensure the install folder (Rubrica) is all
lowercase. Then it will work.

Cheers
Clemens

nanoziobelo ***@***.***> schrieb am Sa. 10. Apr. 2021 um
12:11:

**Comment by cwacha** [comment] 2021-04-11 05:56
Duplicate of #10

**Closed as completed** 2021-04-11 05:56 UTC
